### ISSUE TITLE
risingStone\DailyTask.py执行时报错

### ISSUE THREAD

**Issue by BurningUnder** [FF14CN/Sarean-arsenal#29]
### 问题描述

- 执行risingStones\dailyTask.py:32" - daily_task - INFO - INFO - 当前操作账户 [1] [123****4567]时报错

### 重现步骤

1. 执行python .\run.py
2. 程序在执行到 risingStones\dailyTask.py 时报错并结束

### 截图

以下为命令行输出内容
```
2024-12-12T20:01:18.521182+0800 - "C:\Users\ABC\AppData\Local\Programs\Python\Python310\lib\site-packages\kuai_log\logger.py:214" - get_logger - [print] - 已存在该命名空间 INFO 日志
2024-12-12T20:01:18.521182+0800 - "C:\Users\ABC\AppData\Local\Programs\Python\Python310\lib\site-packages\kuai_log\logger.py:214" - get_logger - [print] - 已存在该命名空间 DEBUG 日志
2024-12-12T20:01:18.522182+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:53" - initialize - INFO - INFO - 检测到存在配置文件，无需进行初始化...
2024-12-12T20:01:18.522182+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:24" - main - INFO - INFO - 读取到了你手动设置的DaoyuKey和ShowUserName
2024-12-12T20:01:18.845718+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:206" - get_account_id_list - INFO - INFO - 当前主账户下存在3个账户.
2024-12-12T20:01:19.784686+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:49" - main - INFO - INFO - 账号123****4567已经签到过了，当前积分余额155000
2024-12-12T20:01:20.826290+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:49" - main - INFO - INFO - 账号1****2@qq.com已经签到过了，当前积分余额4135224
2024-12-12T20:01:21.979796+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:49" - main - INFO - INFO - 账号1****2@163.com已经签到过了，当前积分余额187300
2024-12-12T20:01:22.305558+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:67" - main - INFO - INFO - 推送消息失败，请检查消息推送服务是否配置成功
2024-12-12T20:01:22.610383+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\rs_login.py:172" - rs_get_account_id_list - INFO - INFO - 拉取账号列表成功，当前主账户下发现3个子账户.
2024-12-12T20:01:22.610383+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\dailyTask.py:32" - daily_task - INFO - INFO - 当前操作账户 [1] [123****4567]
Traceback (most recent call last):
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\run.py", line 13, in <module>
    print(lets_go())
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\dailyTask.py", line 37, in daily_task
    daoyu_ticket = dao_login(sub_account_key, cookies)
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\rs_login.py", line 286, in rs_dao_login
    dao_login_json = dao_login_response.json()
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### 运行环境

系统 windows11
Python 3.10.5
本软件版本 2.1.5

**Comment by BurningUnder** [comment]
以下为日志文件
```
2024-12-12T18:13:14.706438+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:18" - main - DEBUG - INFO - Get Config File Success,show_username: 123****4567daoyu_key: DY_******************************21device_id: E6CBDA22-B30F-4BFA-8056-237170F5BDFC-465CB3F2-EE2C-48C0-94BE-EA610743CBE3-31FFB479-7FBC-4CC7-9AA4-9A8E25D22CA4-FBA310F7-A723-4158-A649-A031D4B06C86-B3478C4C-0C79-4ABB-A831-0A79C2464289, manuid: WkRqrv
2024-12-12T18:13:14.842384+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:154" - get_flowid - DEBUG - INFO - Get flowID Successful : 4411E99AAD4248DFAB5CA4D1D37265B0
2024-12-12T18:13:15.253031+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:259" - make_confirm - DEBUG - DEBUG - Confirm with server Successful, AccountID：1234567890
2024-12-12T18:13:15.365881+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:311" - get_sub_account_key - DEBUG - DEBUG - Get_daoyuSubKey Successful
2024-12-12T18:13:16.115250+0800 - DESKTOP-ABC- "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:154" - get_flowid - DEBUG - INFO - Get flowID Successful : C708C36D6CD4439083CBF94B7C81F9B9
2024-12-12T18:13:16.235043+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:259" - make_confirm - DEBUG - DEBUG - Confirm with server Successful, AccountID：1234567890
2024-12-12T18:13:16.341905+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:311" - get_sub_account_key - DEBUG - DEBUG - Get_daoyuSubKey Successful
2024-12-12T18:13:17.112437+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:154" - get_flowid - DEBUG - INFO - Get flowID Successful : 757CD08B5881411E8DD8982988EF73A6
2024-12-12T18:13:17.233894+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:259" - make_confirm - DEBUG - DEBUG - Confirm with server Successful, AccountID：1234567890
2024-12-12T18:13:17.344808+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:311" - get_sub_account_key - DEBUG - DEBUG - Get_daoyuSubKey Successful
2024-12-12T18:13:18.072431+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:68" - main - DEBUG - ERROR - {'status': 'failed', 'error': '{"code":400,"message":"failed to get device token: failed to get [xxxxx] device token from database","timestamp":1733998396}'}
```

**Comment by KuLiPoi** [comment]
可能石之家又改什么参数了 我看看哈

**Comment by KuLiPoi** [comment]
没能复现 有试过重新运行一下吗？

**Comment by BurningUnder** [comment]
今天重新运行仍然报错
```
2024-12-13T14:28:15.080276+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\dailyTask.py:32" - daily_task - INFO - INFO - 当前操作账户 [1] [123****4567]
Traceback (most recent call last):
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\run.py", line 13, in <module>
    print(lets_go())
          ^^^^^^^^^
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\dailyTask.py", line 37, in daily_task
    daoyu_ticket = dao_login(sub_account_key, cookies)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\rs_login.py", line 286, in rs_dao_login
    dao_login_json = dao_login_response.json()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
2024-12-13T14:28:09.863127+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:18" - main - DEBUG - INFO - Get Config File Success,show_username: 123****4567daoyu_key: DY_******************************21device_id: 33E952EF-34D3-4B9E-AF36-585F80CD7F80-294E79BC-CF52-4EE9-A977-211C85FC7400-E67733FC-B109-4AB0-B1D0-33D2A8BCDC3F-D762A41C-E0CD-413B-8BCD-DE6D46088F7B-BCCD34C1-B465-474E-AD2D-130A86117003, manuid: Nl732r
2024-12-13T14:28:10.013357+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:154" - get_flowid - DEBUG - INFO - Get flowID Successful : 44B93903AB604A139C1C3EB4D5429D57
2024-12-13T14:28:10.480012+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:259" - make_confirm - DEBUG - DEBUG - Confirm with server Successful, AccountID：3197252005
2024-12-13T14:28:10.612901+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:311" - get_sub_account_key - DEBUG - DEBUG - Get_daoyuSubKey Successful
2024-12-13T14:28:11.463458+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:154" - get_flowid - DEBUG - INFO - Get flowID Successful : FF28FD69CF1B42FF81FF8A690CB46711
2024-12-13T14:28:11.604254+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:259" - make_confirm - DEBUG - DEBUG - Confirm with server Successful, AccountID：1185669134
2024-12-13T14:28:11.734331+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:311" - get_sub_account_key - DEBUG - DEBUG - Get_daoyuSubKey Successful
2024-12-13T14:28:12.624665+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:154" - get_flowid - DEBUG - INFO - Get flowID Successful : B933CC2C68244EBA9830F8C6E7299F4B
2024-12-13T14:28:12.767522+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:259" - make_confirm - DEBUG - DEBUG - Confirm with server Successful, AccountID：1774812833
2024-12-13T14:28:12.894106+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sm_login.py:311" - get_sub_account_key - DEBUG - DEBUG - Get_daoyuSubKey Successful
2024-12-13T14:28:14.381703+0800 - DESKTOP-ABC - "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\sqMall\sqMallDoSign.py:68" - main - DEBUG - ERROR - {'status': 'failed', 'error': '{"code":400,"message":"failed to get device token: failed to get [xxxxx] device token from database","timestamp":1734071293}'}
```

**Comment by KuLiPoi** [comment]
不好意思前几天阳了又 不太舒服 刚刚我这边又尝试了其他的账号 也不能复现 如果可以的话 能否发送你的 daoyukey 和 showusername 到 邮箱  me@pipirapira.com 在我定位错误之后你可以重新登录叨鱼来重置这些信息不用担心泄露。

**Comment by Clulu1499** [comment]
大佬——我这边也出错了
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SareanFF14\run.py", line 10, in <module>
    sqMallSign.main()
  File "F:\SareanFF14\Utility\sqMall\sqMallDoSign.py", line 40, in main
    sign_msg = daoyumall_sign(sub_account_session, account_id["accountId"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SareanFF14\Utility\sqMall\daoyuBuildinMallSign.py", line 37, in daoyumall_sign
    sign_json = sign_response.json()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
?[0;34m2024-12-16T16:05:51.350765+0800 - "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\kuai_log\logger.py:214" - get_logger - [print] -
已存在该命名空间 INFO 日志
?[0m?[0;34m2024-12-16T16:05:51.350765+0800 - "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\kuai_log\logger.py:214" - get_logger - [print
] - 已存在该命名空间 DEBUG 日志
?[0m?[0;36m2024-12-16T16:05:51.351267+0800 - admin - "F:\SareanFF14\Utility\sqMall\sm_login.py:53" - initialize - INFO - INFO - 检测到存在配置文件，无需进行初始化..
.?[0m
?[0;36m2024-12-16T16:05:51.352270+0800 - admin - "F:\SareanFF14\Utility\sqMall\sqMallDoSign.py:24" - main - INFO - INFO - 读取到了你手动设置的DaoyuKey和ShowUserName
?[0m
?[0;36m2024-12-16T16:05:51.693615+0800 - admin - "F:\SareanFF14\Utility\sqMall\sm_login.py:206" - get_account_id_list - INFO - INFO - 当前主账户下存在2个账户.?[0m
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SareanFF14\run.py", line 10, in <module>
    sqMallSign.main()
  File "F:\SareanFF14\Utility\sqMall\sqMallDoSign.py", line 40, in main
    sign_msg = daoyumall_sign(sub_account_session, account_id["accountId"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SareanFF14\Utility\sqMall\daoyuBuildinMallSign.py", line 37, in daoyumall_sign
    sign_json = sign_response.json()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KuLiPoi** [comment]
麻烦也发一下 上面的那种日志文件 方便排查问题。

**Comment by Clulu1499** [comment]
已经发了——

**Comment by KuLiPoi** [comment]
@Clulu1499 @BurningUnder 请尝试在**Python3.11**的环境下重新执行 程序暂不支持 3.12 的python 等待我后续写新版本的时候再更新吧

**Comment by Clulu1499** [comment]
> @Clulu1499 @BurningUnder 请尝试在**Python3.11**的环境下重新执行 程序暂不支持 3.12 的python 等待我后续写新版本的时候再更新吧

好哦 感谢佬——

**Comment by BurningUnder** [comment]
不好意思，请问使用3.11的哪个版本可以呢？
刚才使用python 3.11.9依然报相同的错误
```
Traceback (most recent call last):
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\run.py", line 13, in <module>
    print(lets_go())
          ^^^^^^^^^
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\dailyTask.py", line 37, in daily_task
    daoyu_ticket = dao_login(sub_account_key, cookies)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\rs_login.py", line 286, in rs_dao_login
    dao_login_json = dao_login_response.json()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by KuLiPoi** [comment]
@BurningUnder 我这边使用的是3.11.5 如果使用3.11.5还是不能使用麻烦告知我 我今晚进行更新一下

**Comment by BurningUnder** [comment]
使用3.11.5还是报相同的错误
```
Traceback (most recent call last):
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\run.py", line 13, in <module>
    print(lets_go())
          ^^^^^^^^^
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\dailyTask.py", line 37, in daily_task
    daoyu_ticket = dao_login(sub_account_key, cookies)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ABC\Sarean-arsenal-2.1.5\Sarean-arsenal-2.1.5\Utility\risingStones\rs_login.py", line 286, in rs_dao_login
    dao_login_json = dao_login_response.json()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ABC\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Clulu1499** [comment]
@BurningUnder py升级到3.13.0能用了【
